# Generated by Django 5.2.16 on 2026-09-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='Janaki Power Engineering Co. Pvt. Ltd.', help_text='Full registered company name.', max_length=255)),
                ('company_short_name', models.CharField(default='JPEC', help_text='Short brand name / acronym displayed in the logo and navbar.', max_length=50)),
                ('tagline', models.CharField(default="A trusted name in Nepal's engineering sector", help_text='Company tagline or slogan.', max_length=255)),
                ('company_description', models.TextField(default='A leading engineering company in Nepal specializing in cold storage, water systems, dairy processing, steel fabrication, solar energy, and construction.', help_text='Brief company description used across the footer and meta tags.')),
                ('founding_year', models.CharField(default='1998', help_text='Year the company was established (e.g. 1998).', max_length=10)),
                ('company_type', models.CharField(default='Private Limited', help_text='e.g. Private Limited', max_length=100)),
                ('registration_number', models.CharField(default='Reg. 12345/2055', help_text='Company registration number.', max_length=100)),
                ('pan_vat_number', models.CharField(default='300XXXXXXX', help_text='PAN/VAT registration number.', max_length=50)),
                ('employee_count', models.CharField(default='150+', help_text='e.g. 150+', max_length=50)),
                ('primary_phone', models.CharField(default='+977-071-523456', help_text='Primary telephone number displayed in top bar and footer.', max_length=50)),
                ('secondary_phone', models.CharField(blank=True, default='+977-9857012345', help_text='Secondary mobile/contact number.', max_length=50)),
                ('primary_email', models.EmailField(default='info@jpec.com.np', help_text='Primary email address for inquiries.', max_length=254)),
                ('secondary_email', models.EmailField(blank=True, default='jpec.nepal@gmail.com', help_text='Secondary email address.', max_length=254)),
                ('address', models.CharField(default='Butwal-11, Rupandehi, Lumbini Province, Nepal', help_text='Physical head office address.', max_length=255)),
                ('business_hours', models.CharField(default='Mon - Sat: 9:00 AM - 6:00 PM', help_text='Operating business hours.', max_length=100)),
                ('map_location_text', models.TextField(default='JPEC is located in Butwal-11, Rupandehi, approximately 300m from Butwal Bus Park on the Butwal–Bhairahawa Highway.', help_text='Directions / location guidance text for the contact page.')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com', help_text='Facebook page URL.')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com', help_text='Twitter / X profile URL.')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com', help_text='LinkedIn page URL.')),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com', help_text='YouTube channel URL.')),
                ('hero_badge', models.CharField(default='Engineering Excellence', help_text='Small badge text above the hero heading.', max_length=100)),
                ('hero_heading', models.CharField(default='Janaki Power Engineering Co. Pvt. Ltd.', help_text='Main heading on the homepage hero.', max_length=255)),
                ('hero_subtext', models.TextField(default="A trusted name in Nepal's engineering sector — delivering integrated solutions in cold storage, water treatment, dairy processing, steel fabrication, renewable energy, and construction since 1998.", help_text='Hero paragraph text.')),
                ('hero_image', models.ImageField(blank=True, help_text='Optional custom hero background image. If omitted, default image is used.', null=True, upload_to='site_settings/hero/')),
                ('hero_cta_primary_label', models.CharField(default='About Us', help_text='Label for primary hero CTA button.', max_length=50)),
                ('hero_cta_primary_link', models.CharField(default='/about/introduction', help_text='URL or path for primary hero CTA button.', max_length=255)),
                ('hero_cta_secondary_label', models.CharField(default='Contact Us', help_text='Label for secondary hero CTA button.', max_length=50)),
                ('hero_cta_secondary_link', models.CharField(default='/contact-us', help_text='URL or path for secondary hero CTA button.', max_length=255)),
                ('stat_years_experience', models.CharField(default='25+', help_text="Years of experience counter display (e.g. '25+').", max_length=20)),
                ('stat_projects_completed', models.CharField(default='500+', help_text="Projects completed counter display (e.g. '500+').", max_length=20)),
                ('stat_happy_clients', models.CharField(default='300+', help_text="Happy clients counter display (e.g. '300+').", max_length=20)),
                ('stat_business_sectors', models.CharField(default='6', help_text="Business sectors counter display (e.g. '6').", max_length=20)),
                ('cta_heading', models.CharField(default='Ready to Start Your Project?', help_text='Heading for bottom CTA banner.', max_length=255)),
                ('cta_subtext', models.CharField(default='Contact our engineering team for a free consultation and project estimate.', help_text='Subtext for bottom CTA banner.', max_length=255)),
                ('cta_button_label', models.CharField(default='Get In Touch', help_text='CTA button label.', max_length=50)),
                ('cta_button_link', models.CharField(default='/contact-us', help_text='CTA button link destination.', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
