# Generated by Django 5.2.16 on 2026-09-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="Internal slide reference title (e.g. 'Turnkey Machinery Slide').", max_length=255)),
                ('badge', models.CharField(blank=True, help_text='Optional small pill badge above heading.', max_length=100)),
                ('heading', models.CharField(help_text='Main headline for this slide.', max_length=255)),
                ('subtext', models.TextField(blank=True, help_text='Descriptive paragraph text.')),
                ('image', models.ImageField(help_text='Background hero machinery photo.', upload_to='site_settings/hero_slides/')),
                ('primary_cta_label', models.CharField(blank=True, default='Explore Machinery', help_text='Primary button text.', max_length=50)),
                ('primary_cta_link', models.CharField(blank=True, default='/products', help_text='Primary button link destination.', max_length=255)),
                ('secondary_cta_label', models.CharField(blank=True, default='Request a Quote', help_text='Secondary button text.', max_length=50)),
                ('secondary_cta_link', models.CharField(blank=True, default='/contact-us#quote', help_text='Secondary button link destination.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Slide display order.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slide is active on the homepage carousel.')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Official company logo image. If omitted, default logo is used.', null=True, upload_to='site_settings/logo/'),
        ),
    ]
