# Generated by Django 5.2.16 on 2026-09-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_heroslide_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='iso_accreditation',
            field=models.CharField(default='URS / UKAS Management Systems (0043) / IAF Multilateral Recognition Arrangement', help_text='Accreditation and registrar bodies.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='iso_certificate_image',
            field=models.ImageField(blank=True, help_text='Official ISO registration certificate image (.webp).', null=True, upload_to='site_settings/certificates/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='iso_certificate_number',
            field=models.CharField(default='129594/A/0001/UK/En', help_text='Official registration certificate number.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='iso_certified',
            field=models.BooleanField(default=True, help_text='Whether the company holds active ISO certification.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='iso_expiry_date',
            field=models.CharField(default='17 November 2026', help_text='Certificate expiry date.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='iso_issue_date',
            field=models.CharField(default='18 November 2023', help_text='Certificate issue date.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='iso_scope',
            field=models.TextField(default="Manufacturing and Assembly of Reverse Osmosis Plant, Dairy Equipment's (Pasteurizer, Homogenizer, Chilling Vat, Road Milk Tanker), Cold Storage Equipment's, Solar Energy & Heat Pump System, Steel Fabrication", help_text='Scope of activities covered by this certificate.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='iso_standard',
            field=models.CharField(default='ISO 9001:2015', help_text="ISO standard name (e.g. 'ISO 9001:2015').", max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='Kathmandu, Nepal', help_text='Physical head office address.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='JP Engineering & Construction Pvt. Ltd.', help_text='Full registered company name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_short_name',
            field=models.CharField(default='JP Engineering & Construction Pvt. Ltd.', help_text='Short brand name / acronym displayed in the logo and navbar.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_heading',
            field=models.CharField(default='JP Engineering & Construction Pvt. Ltd.', help_text='Main heading on the homepage hero.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_location_text',
            field=models.TextField(default='Kathmandu, Nepal', help_text='Directions / location guidance text for the contact page.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='pan_vat_number',
            field=models.CharField(blank=True, default='', help_text='PAN/VAT registration number.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_phone',
            field=models.CharField(default='01-5385552', help_text='Primary telephone number displayed in top bar and footer.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='registration_number',
            field=models.CharField(blank=True, default='', help_text='Company registration number.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_email',
            field=models.EmailField(blank=True, default='', help_text='Secondary email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_phone',
            field=models.CharField(blank=True, default='9851112988, 9851158661, 9851158660', help_text='Secondary mobile/contact numbers.', max_length=255),
        ),
    ]
