# Generated by Django 5.2.16 on 2026-09-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_sitesettings_iso_accreditation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, default='https://tiktok.com', help_text='TikTok profile URL.'),
        ),
    ]
