# Generated by Django 5.2.16 on 2026-09-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_sitesettings_tiktok_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district_name', models.CharField(help_text='Official district name matching the SVG map (e.g. Kathmandu, Kaski, Morang).', max_length=100, unique=True)),
                ('province', models.CharField(choices=[('Koshi', 'Koshi Province'), ('Madhesh', 'Madhesh Province'), ('Bagmati', 'Bagmati Province'), ('Gandaki', 'Gandaki Province'), ('Lumbini', 'Lumbini Province'), ('Karnali', 'Karnali Province'), ('Sudurpashchim', 'Sudurpashchim Province')], help_text='Province where this district is located.', max_length=50)),
                ('is_highlighted', models.BooleanField(db_index=True, default=False, help_text='Whether this district is highlighted on the Nepal map.')),
                ('projects_count', models.PositiveIntegerField(default=1, help_text='Number of completed or active engineering projects in this district.')),
                ('services_summary', models.CharField(blank=True, help_text='Key services or machines installed (e.g. Cold Storage, RO Water Plant, Dairy).', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed project summary or case study notes displayed on hover / click.')),
                ('highlight_color', models.CharField(default='#c8391a', help_text='Custom highlight color hex (defaults to brand accent #c8391a).', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in district lists.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this district record is active in the CMS.')),
            ],
            options={
                'verbose_name': 'District Coverage',
                'verbose_name_plural': 'District Coverages',
                'ordering': ['-is_highlighted', 'order', 'district_name'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='coverage_badge',
            field=models.CharField(default='Nationwide Presence', help_text='Small pill badge text above the coverage map heading.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='coverage_heading',
            field=models.CharField(default='Our Engineering Services Across Nepal', help_text='Main heading for the Nepal coverage map section.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='coverage_is_active',
            field=models.BooleanField(default=True, help_text='Whether to display the Nepal coverage map section on the homepage.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='coverage_stat_districts',
            field=models.CharField(default='25+', help_text="Districts covered counter display (e.g. '25+').", max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='coverage_stat_projects',
            field=models.CharField(default='150+', help_text="Projects completed counter display (e.g. '150+').", max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='coverage_stat_provinces',
            field=models.CharField(default='7', help_text="Provinces covered counter display (e.g. '7').", max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='coverage_subtext',
            field=models.TextField(default='From industrial cold storage and commercial reverse osmosis water treatment plants to dairy processing machinery, solar setups, and structural steel fabrication — explore the districts across Nepal where JP Engineering & Construction delivers trusted engineering solutions.', help_text='Descriptive subtext for the coverage map section.'),
        ),
    ]
