# Generated by Django 5.2.16 on 2026-09-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(help_text='The question text.', max_length=500)),
                ('answer', models.TextField(help_text='The detailed answer text.')),
                ('page', models.CharField(choices=[('all', 'All Pages / Global'), ('products', 'Products Page & Catalog'), ('industries', 'Industries We Serve'), ('contact', 'Contact Us'), ('introduction', 'About Us - Introduction'), ('company-profile', 'About Us - Company Profile'), ('our-team', 'About Us - Our Team'), ('our-clients', 'About Us - Our Clients'), ('our-partners', 'About Us - Business Partners')], default='all', help_text='Target subpage where this FAQ is displayed.', max_length=50)),
                ('category', models.CharField(blank=True, default='', help_text='Optional topic category (e.g. Fabrication, Warranty, Commissioning).', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first).')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this FAQ is published and visible on the website.')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='full_intro',
            field=models.TextField(default='JP Engineering & Construction Pvt. Ltd. is a leading manufacturer and supplier of machinery for various industrial sectors since 10 years. Our product range includes machinery for community-based water treatment systems, industrial water plants, dairy plants, industrial refrigeration, solar energy and irrigation, solar energy and heat pump system and meat mincing and packaging.\n\nThe company provides water treatment systems for schools, colleges, hospitals, public institutions, and corporate houses. These systems are designed to effectively treat water and make it safe for human consumption. The industrial water plants offered by the company include equipment for the bottle and jar sections, ensuring efficient water processing for industrial use.\n\nIn the dairy industry, JP Engineering & Construction Pvt. Ltd. provides machinery for the production of various dairy products such as pouch milk, curd, ghee, ice cream, cheese, panir, khuwa, and bottled dairy products. Their dairy industrial plant machinery is designed to meet the highest standards of quality and efficiency.\n\nThe company also specializes in industrial refrigeration systems, providing equipment for the storage of vaccines, vegetables, fruits, dairy products, medicines, and similar products. We offer complete solutions, including refrigeration units and their necessary spare parts and equipment.\n\nJP Engineering & Construction Pvt. Ltd. is also a leader in the development of solar energy and irrigation systems. Their solar irrigation systems use solar power to provide water for irrigation, making them environmentally friendly and cost-effective. Additionally, the company provides solar energy and heat pump systems for hotels, hostels, hospitals, and corporate houses, ensuring energy efficiency and cost savings.\n\nIn addition to the above, the company is also involved in steel fabrication work, which includes tanker fabrication, SS tank fabrication, vessel fabrication, basin fabrication, kitchen shelf fabrication, and other equipment fabrication. The company is looking to expand its scope of operations into the construction industry, and has already begun offering construction services to its clients.\n\nFinally, the company offers meat mincing and packaging machinery, including meat grinders, vacuum packaging machines, plastic sealer machines, sausage stuffers, and similar equipment. These machines are designed to meet the needs of the meat processing industry and are built to the highest standards of quality and performance.\n\nIn conclusion, JP Engineering & Construction Pvt. Ltd. is a one-stop solution for all machinery needs in various industrial sectors including some construction work (the scope of construction is limited at the moment at JP Engineering but we are looking forward to increasing our working area in the field of construction as well). We provide high-quality and efficient machinery, designed to meet the specific needs of our clients along with technical support, with a focus on customer satisfaction and a commitment to excellence. JP Engineering & Construction Pvt. Ltd. is a reliable and trustworthy partner for all machinery needs.', help_text='Full introduction displayed on the /about/introduction page.'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='short_intro',
            field=models.TextField(default='JP Engineering & Construction Pvt. Ltd. is a leading manufacturer and supplier of machinery for various industrial sectors since 10 years. Our product range includes machinery for community-based water treatment systems, industrial water plants, dairy plants, industrial refrigeration, solar energy and irrigation, solar energy and heat pump system and meat mincing and packaging. The company provides water treatment systems for schools, colleges, hospitals, public institutions, and corporate houses.', help_text='Short introduction displayed on the home page.'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='title',
            field=models.CharField(default='JP Engineering & Construction Pvt. Ltd.', help_text='Company or site title.', max_length=255),
        ),
    ]
