# Generated by Django 5.2.16 on 2026-09-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faq_alter_sitecontent_full_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='page',
            field=models.CharField(choices=[('all', 'All Pages / Global'), ('products', 'Products Page & Catalog'), ('product-detail', 'Product Detail Pages'), ('industries', 'Industries We Serve'), ('industry-detail', 'Industry Detail Pages'), ('contact', 'Contact Us'), ('introduction', 'About Us - Introduction'), ('company-profile', 'About Us - Company Profile'), ('our-team', 'About Us - Our Team'), ('our-clients', 'About Us - Our Clients'), ('our-partners', 'About Us - Business Partners')], default='all', help_text='Target subpage where this FAQ is displayed.', max_length=50),
        ),
    ]
