# Generated by Django 5.2.16 on 2026-09-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_industry'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='products', to='categories.industry'),
        ),
    ]
